### ISSUE TITLE
Adding frontmatter plugin to Svite-routify-mdsvex starter gives warning and breaks routify

### ISSUE THREAD

**Issue by rustybuddha** [jakobrosenberg/routify-plugin-frontmatter#1]
### This is the warning:

[Routify] Watching src/pages
(node:1722575) YAMLWarning: Keys with collection values will be stringified as YAML due to JS Object restrictions. Use mapAsMap: true to avoid this.
(node:1722575) UnhandledPromiseRejectionWarning: YAMLSyntaxError: All collection items must start at the same column
    at Collection.parse (/projects/home.online/node_modules/yaml/dist/parse-cst.js:331:24)
    at ~/projects/home.online/node_modules/yaml/dist/parse-cst.js:1605:29
    at Document.parseContents (/projects/home.online/node_modules/yaml/dist/parse-cst.js:622:26)
    at Document.parse (/projects/home.online/node_modules/yaml/dist/parse-cst.js:685:19)
    at Object.parse (/projects/home.online/node_modules/yaml/dist/parse-cst.js:1723:18)
    at parseDocument (/projects/home.online/node_modules/yaml/dist/index.js:43:24)
    at Object.parse (/projects/home.online/node_modules/yaml/dist/index.js:55:15)
    at walkFiles (/projects/home.online/node_modules/routify-plugin-frontmatter/index.js:25:53)
    at Array.map (<anonymous>)
    at walkFiles (/projects/home.online/node_modules/routify-plugin-frontmatter/index.js:20:45)
(node:1722575) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1722575) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Routify stops working properly after this. New routes are not detected, with the error:
[Routify] ✖ Failed to generate route files YAMLSyntaxError: All collection items must start at the same column
    at Collection.parse (/projects/home.online/node_modules/yaml/dist/parse-cst.js:331:24)
    at ~/projects/home.online/node_modules/yaml/dist/parse-cst.js:1605:29
    at Document.parseContents (/projects/home.online/node_modules/yaml/dist/parse-cst.js:622:26)
    at Document.parse (/projects/home.online/node_modules/yaml/dist/parse-cst.js:685:19)
    at Object.parse (/projects/home.online/node_modules/yaml/dist/parse-cst.js:1723:18)
    at parseDocument (/projects/home.online/node_modules/yaml/dist/index.js:43:24)
    at Object.parse (/projects/home.online/node_modules/yaml/dist/index.js:55:15)
    at walkFiles (/projects/home.online/node_modules/routify-plugin-frontmatter/index.js:25:53)
    at Array.map (<anonymous>)
    at walkFiles (/projects/home.online/node_modules/routify-plugin-frontmatter/index.js:20:45) {
  source: Collection {
    error: [Circular],
    range: Range { start: 5, end: 2756 },
    valueRange: Range { start: 5, end: 2755 },
    props: [],
    type: 'MAP',
    value: null,
    items: [
      [PlainValue],     [CollectionItem], [FlowCollection],
      [CollectionItem], [FlowCollection], [CollectionItem],
      [BlankLine],      [PlainValue],     [CollectionItem],
      [BlankLine],      [PlainValue],     [CollectionItem],
      [FlowCollection], [PlainValue],     [BlankLine],
      [PlainValue],     [CollectionItem], [FlowCollection],
      [FlowCollection], [BlankLine],      [FlowCollection],
      [CollectionItem], [BlankLine],      [PlainValue],
      [BlankLine],      [PlainValue],     [PlainValue],
      [PlainValue],     [PlainValue],     [BlankLine],
      [PlainValue],     [PlainValue],     [PlainValue],
      [PlainValue],     [BlankLine],      [PlainValue],
      [PlainValue],     [PlainValue],     [PlainValue],
      [BlankLine],      [PlainValue],     [BlankLine],
      [BlockValue],     [PlainValue],     [BlockValue],
      [PlainValue],     [BlockValue],     [PlainValue],
      [BlockValue],     [PlainValue],     [BlockValue],
      [PlainValue],     [BlankLine],      [PlainValue],
      [PlainValue],     [PlainValue],     [BlankLine],
      [PlainValue]
    ],
    resolved: YAMLMap {
      items: [Array],
      schema: undefined,
      range: [Array],
      type: 'MAP',
      spaceBefore: true
    }
  }
}

**Comment by jakobrosenberg** [comment]
Thanks for posting this @rustybuddha.

@dominikg any idea what this could be?

**Comment by dominikg** [comment]
hmm, reads like a formatting issue in frontmatter.
@rustybuddha can you post the frontmatter that causes this?

**Comment by rustybuddha** [comment]
Without any frontmatter also, it fails, if it just has an a tag.
I found that adding
`<a href="https://anything">check it out</a>`
in any .svx file breaks it when routify-plugin-frontmatter is added to plugin in routify.config.js.
This is not a problem though, as markdown anyway does not need a tag.

**Comment by jakobrosenberg** [comment]
Thanks for the feedback on this. I'll close it.  🙂

**Comment by rustybuddha** [comment]
I had the 3 dashes separating each header cell from the rest of the table in markdown.
This was getting detected as front-matter and causing the problem.
It is working now with a tags also. But there seemed to be some flaky inconsistent behavior which I had got while adding and removing a tags, to find the source of the error.
The problem seems to be solved though..
